Repository w3ctag/privacy-principles, pull requests merged in 2022-04, with the labels that each got.

#105 Discuss tensions between principles.
  index.html
Labels: agenda+

#132 Added notifications principles
  index.html
Labels: agenda+

#139 Refine and clarify the definitions of first and third parties.
  index.html
Labels: agenda+

#141 Add a non-retaliation principle
  index.html
Labels: agenda+

#14 Make the orange box go away.
  index.html
Labels: agenda+, ready to merge

#148 Alphabetize Appendix B (High-Level Threats)
  index.html
Labels: editorial
